### ISSUE TITLE
Project Installation Instruction FAILS on Windows

### ISSUE THREAD

**Issue by gdvallance** [ouh-churchill/diakonia#57]
Running _equivalent_ of  `
    pip install -r diakonia-repo/requirements/development.txt` fails on Windows.

Specifically, 

```
Requirement already satisfied (use --upgrade to upgrade): lxml in c:\users\grant.vallance\appdata\local\continuum\anaconda3\lib\site-packages (from -r requirements\common.txt (line 10))
Collecting gnureadline (from -r requirements\development.txt (line 4))
  Downloading gnureadline-6.3.3.tar.gz (2.5MB)
    100% |################################| 2.5MB 403kB/s
    Complete output from command python setup.py egg_info:
    Error: this module is not meant to work on Windows (try pyreadline instead)

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\GRANT~1.VAL\AppData\Local\Temp\pip-build-v3sp13hv\gnureadline\

```

So DEV requirements not cross-platform.

RECOMMENDATION: (1) Make DEV requirements cross-platform; OR/ (2) Create separate Windows/Linux install instructions.

**Comment by marshalc** [comment]
To shorten the Slack hosted discussion on this topic:
- GV has a mixed environment with an Anaconda system setup, and a non-isolated virtualenv, prompting the message about lxml needing the upgrade flag
- gnureadline is a *nix only solution it seems as there isn't a windows c-library for deadline. Solution here was for a new requirements file to be created for windows requirements, and to swap gnureadline there for pyreadline, which is a windows equivalent implementation
- The next (not reported here) issue is that pyenchant does not have a working build for Win64, so we're going to open a new issue about that, and potentially remove it from the build by taking it out of the Sphinx config
